### ISSUE TITLE
Unique key for individual tx: payload id + mobile number?

### ISSUE THREAD

**Issue by Stadicus** [MuleTools/PonyDirect#6]
I am trying to build a simple SMS-to-Bitcoin gateway for my [RaspiBolt](https://github.com/Stadicus/guides/blob/master/raspibolt/README.md) project, using a python program to parse incoming SMS messages.

To build the correct data array, I need to be able to group the various SMS together, probably using the payload id. My guess is that this is a simple counter, incremented by the sending client for each transaction. This way, I would need to capture the senders mobile# as well to combine these two fields for a unique key. Are my assumptions correct? Is this the way to go, or is it possible to ignore the sender's mobile# from the start?

Thanks for your great contribution with Samourai & this new project, you are leading by example! :-)

**Comment by SamouraiDev** [comment]
Your assumption is correct. We identify messages by mobile number + message id, the message id being a simple counter.
